/**
 * Optional on-disk recording of finished sessions.
 *
 * - Disabled unless a directory is configured. Payloads are excluded unless
 *   `includePayloads` is set (DECISIONS.md D-010).
 * - File names are generated by the server (`<UTC timestamp>-<session id>.tfrec.json`), never
 *   taken from a request. The directory is created with mode 0700 and files with 0600, and an
 *   existing file is never overwritten.
 * - Retention: keeps at most `maxFiles` recordings and deletes recordings older than
 *   `maxAgeDays`. Only files matching the TokenFault naming pattern are touched.
 * - Failures are logged and never affect proxied traffic.
 */
import { mkdir, readdir, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createRecording, serializeRecording } from '@tokenfault/core';
import { describeError } from '@tokenfault/shared';
import type { FastifyBaseLogger } from 'fastify';
import type { Session } from './session-store.js';

export interface RecorderOptions {
  readonly dir: string;
  readonly includePayloads: boolean;
  readonly maxFiles: number;
  readonly maxAgeDays: number;
  readonly toolVersion: string;
  readonly logger: FastifyBaseLogger;
}

const RECORDING_NAME = /^\d{8}T\d{6}Z-[A-Za-z0-9_-]{1,64}\.tfrec\.json$/;

export class SessionRecorder {
  private ready: Promise<void> | null = null;
  private queue: Promise<void> = Promise.resolve();

  constructor(private readonly options: RecorderOptions) {}

  /** Queues a session for writing. Writes are serialised to keep retention consistent. */
  record(session: Session): Promise<void> {
    this.queue = this.queue
      .then(() => this.write(session))
      .catch((error: unknown) => {
        this.options.logger.warn(
          { session: session.id, err: describeError(error) },
          'failed to write recording',
        );
      });
    return this.queue;
  }

  /** Resolves once all queued writes finished. */
  flush(): Promise<void> {
    return this.queue;
  }

  private async write(session: Session): Promise<void> {
    this.ready ??= this.prepareDir();
    await this.ready;
    const recording = createRecording(session.detail(), {
      includePayloads: this.options.includePayloads,
      toolVersion: this.options.toolVersion,
      seed: session.seed,
    });
    const stamp = new Date(session.meta.startedAt)
      .toISOString()
      .replace(/[-:]/g, '')
      .replace(/\.\d{3}Z$/, 'Z');
    const name = `${stamp}-${session.id}.tfrec.json`;
    if (!RECORDING_NAME.test(name))
      throw new Error(`Refusing to write unexpected recording file name ${JSON.stringify(name)}`);
    await writeFile(path.join(this.options.dir, name), serializeRecording(recording), {
      mode: 0o600,
      flag: 'wx',
    });
    await this.applyRetention();
  }

  /**
   * Creates the directory with mode 0700. An existing directory chosen by the user is not
   * chmod-ed, but a warning is logged if other users can access it.
   */
  private async prepareDir(): Promise<void> {
    await mkdir(this.options.dir, { recursive: true, mode: 0o700 });
    const info = await stat(this.options.dir);
    if (process.platform !== 'win32' && (info.mode & 0o077) !== 0) {
      this.options.logger.warn(
        { dir: this.options.dir, mode: (info.mode & 0o777).toString(8) },
        'recording directory is accessible to other users; recordings themselves are written with mode 0600',
      );
    }
  }

  private async applyRetention(): Promise<void> {
    const entries = (await readdir(this.options.dir)).filter((n) => RECORDING_NAME.test(n)).sort();
    const cutoff = Date.now() - this.options.maxAgeDays * 24 * 60 * 60 * 1000;
    const excess = entries.length - this.options.maxFiles;
    for (const [index, name] of entries.entries()) {
      const full = path.join(this.options.dir, name);
      let remove = index < excess;
      if (!remove) {
        const info = await stat(full);
        remove = info.mtimeMs < cutoff;
      }
      if (remove) await unlink(full);
    }
  }
}
